import { EntityConfig, EntityId } from "@/types/entity";

export const INDIA_CENTER: [number, number] = [78.9629, 20.5937]; // [lng, lat]
export const INDIA_DEFAULT_ZOOM = 4.8;

export const ENTITY_CONFIGS: Record<EntityId, EntityConfig> = {
  all: {
    id: "all",
    name: "All Impact View",
    shortName: "All Impact",
    tagline: "System-wide Footprint",
    description:
      "Comprehensive visualization of Aravind Eye Care System's global presence across healthcare, research, manufacturing, capacity building, and technology.",
    color: "#D97706", // Gold
    colorLight: "#FBBF24",
    bgGlow: "rgba(217, 119, 6, 0.15)",
    subcategories: [
      {
        id: "all_locations",
        name: "All Entities Overview",
        tagline: "Combined geographic presence",
        defaultScope: "country",
        primaryMetricKey: "totalEntities",
        secondaryMetricKeys: ["locationsCount", "countriesCount"],
        legendTitle: "Entity Types",
      },
    ],
    metrics: [
      { id: "totalLocations", label: "Global Locations" },
      { id: "entitiesCount", label: "Entities Represented" },
      { id: "statesCount", label: "Indian States" },
      { id: "countriesCount", label: "Countries Served" },
    ],
    defaultCenter: INDIA_CENTER,
    defaultZoom: INDIA_DEFAULT_ZOOM,
  },
  hospitals: {
    id: "hospitals",
    name: "Aravind Eye Hospitals",
    shortName: "Eye Hospitals",
    tagline: "Care",
    description:
      "Network of tertiary, secondary, outpatient eye care hospitals and vision centres providing high-quality, compassionate eye care.",
    color: "#2563EB", // Deep Blue
    colorLight: "#60A5FA",
    bgGlow: "rgba(37, 99, 235, 0.15)",
    subcategories: [
      {
        id: "hospitals_tertiary",
        name: "Tertiary",
        tagline: "8 Tertiary Super-Specialty Eye Care Centres",
        defaultScope: "state",
        primaryMetricKey: "tertiaryCount",
        secondaryMetricKeys: ["bedsCount", "surgeriesCount"],
        legendTitle: "Tertiary Eye Hospitals",
      },
      {
        id: "hospitals_secondary",
        name: "Secondary",
        tagline: "8 Secondary Regional Eye Care Centres",
        defaultScope: "state",
        primaryMetricKey: "secondaryCount",
        secondaryMetricKeys: ["bedsCount", "outpatientCount"],
        legendTitle: "Secondary Eye Hospitals",
      },
      {
        id: "hospitals_community",
        name: "Community Eye Clinic",
        tagline: "8 Community Eye Clinics & Outpatient Centres",
        defaultScope: "state",
        primaryMetricKey: "communityCount",
        secondaryMetricKeys: ["clinicsCount", "outpatientReach"],
        legendTitle: "Community Eye Clinics",
      },
      {
        id: "hospitals_vision_centres",
        name: "Vision Centres",
        tagline: "Primary IT-enabled rural vision centers",
        defaultScope: "state",
        primaryMetricKey: "visionCentresCount",
        secondaryMetricKeys: ["teleconsults", "ruralCoverage"],
        legendTitle: "Rural Vision Centres",
      },
      {
        id: "patients",
        name: "Patients",
        tagline: "Outpatient and surgical volume reach",
        defaultScope: "state",
        primaryMetricKey: "annualOutpatients",
        secondaryMetricKeys: ["surgeriesCount", "freeCarePercent"],
        legendTitle: "Patient Density",
      },
      {
        id: "staffs",
        name: "Staffs",
        tagline: "Ophthalmologists, MLOPs & administrative workforce",
        defaultScope: "state",
        primaryMetricKey: "staffCount",
        secondaryMetricKeys: ["doctorsCount", "mlopCount"],
        legendTitle: "Workforce Strength",
      },
    ],
    metrics: [
      { id: "hospitalsCount", label: "Eye Care Centres" },
      { id: "bedsCount", label: "Hospital Beds" },
      { id: "annualOutpatients", label: "Annual Outpatients" },
      { id: "surgeriesCount", label: "Surgeries Performed" },
    ],
    defaultCenter: [78.1198, 9.9252],
    defaultZoom: 6.2,
  },
  laico: {
    id: "laico",
    name: "Lions Aravind Institute of Community Ophthalmology",
    shortName: "LAICO",
    tagline: "Capacity Building",
    description:
      "Global consultancy and training institute expanding high-volume, high-quality eye care through partner hospitals across 30+ nations.",
    color: "#0D9488", // Teal
    colorLight: "#2DD4BF",
    bgGlow: "rgba(13, 148, 136, 0.15)",
    subcategories: [
      {
        id: "capacity_building",
        name: "Capacity Building",
        tagline: "Mentored partner hospitals worldwide",
        defaultScope: "world",
        primaryMetricKey: "partnerHospitals",
        secondaryMetricKeys: ["surgeriesMentored", "efficiencyGain"],
        legendTitle: "Partner Network",
      },
      {
        id: "management_courses",
        name: "Management Courses",
        tagline: "Hospital management & executive leadership (2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Management Course Alumni",
      },
      {
        id: "long_term_trainees",
        name: "Long Term Trainees",
        tagline: "Long term clinical fellowships (2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Long Term Fellows",
      },
      {
        id: "short_term_trainees",
        name: "Short Term Trainees",
        tagline: "Short term specialized clinical training (855 Trainees, 2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Short Term Trainees",
      },
      {
        id: "post_graduates",
        name: "Post Graduates",
        tagline: "Post graduate residency & academic specialization (2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Post Graduate Scholars",
      },
      {
        id: "technicians",
        name: "Technicians",
        tagline: "Ophthalmic & instrument maintenance technicians (2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Technicians",
      },
      {
        id: "paramedics",
        name: "Paramedics",
        tagline: "Mid-level ophthalmic personnel & nursing (2017 – 2026)",
        defaultScope: "world",
        primaryMetricKey: "participantsCount",
        secondaryMetricKeys: ["coursesCount", "nationsRepresented"],
        legendTitle: "Paramedics",
      },
    ],
    metrics: [
      { id: "partnerHospitals", label: "Mentored Hospitals" },
      { id: "participantsCount", label: "Trained Executives" },
      { id: "countriesCount", label: "Countries Engaged" },
      { id: "coursesCount", label: "Training Programs" },
    ],
    defaultCenter: [78.9629, 20.5937],
    defaultZoom: 4.5,
  },
  amrf: {
    id: "amrf",
    name: "Aravind Medical Research Foundation",
    shortName: "AMRF",
    tagline: "Research",
    description:
      "Premieres basic research in ocular science, molecular genetics, proteomics, stem cells, and clinical research.",
    color: "#7C3AED", // Purple
    colorLight: "#A78BFA",
    bgGlow: "rgba(124, 58, 237, 0.15)",
    subcategories: [
      {
        id: "doctorate",
        name: "Doctorate",
        tagline: "Ph.D. Doctoral scholars (Completed & Registered)",
        defaultScope: "state",
        primaryMetricKey: "phdCount",
        secondaryMetricKeys: ["publications", "citations"],
        legendTitle: "Ph.D. Scholars",
      },
      {
        id: "collaboratives",
        name: "Collaboratives",
        tagline: "Global academic & institutional research partners",
        defaultScope: "world",
        primaryMetricKey: "collaborationsCount",
        secondaryMetricKeys: ["jointPapers", "activeGrants"],
        legendTitle: "Research Partners",
      },
      {
        id: "students_abroad",
        name: "Students from abroad",
        tagline: "International research fellows & visiting scholars",
        defaultScope: "world",
        primaryMetricKey: "internationalStudents",
        secondaryMetricKeys: ["nationsRepresented", "researchFellows"],
        legendTitle: "Global Scholars",
      },
    ],
    metrics: [
      { id: "phdCompletedCount", label: "Ph.D. Graduates" },
      { id: "ongoingPhdCount", label: "Current Scholars" },
      { id: "publicationsCount", label: "Peer-Reviewed Papers" },
      { id: "globalPartnersCount", label: "Global Research Partners" },
    ],
    defaultCenter: [78.1198, 9.9252],
    defaultZoom: 6.0,
  },
  aurolab: {
    id: "aurolab",
    name: "Aurolab",
    shortName: "Aurolab",
    tagline: "Access",
    description:
      "Manufacturing division producing high-quality intraocular lenses, suture materials, pharmaceutical eye drops, and surgical equipment for worldwide blindness prevention.",
    color: "#EA580C", // Warm Orange
    colorLight: "#FB923C",
    bgGlow: "rgba(234, 88, 12, 0.15)",
    subcategories: [
      {
        id: "domestic",
        name: "Domestic",
        tagline: "42 Domestic Dealers across India",
        defaultScope: "state",
        primaryMetricKey: "dealersCount",
        secondaryMetricKeys: ["dealersCovered", "productsDistributed"],
        legendTitle: "Domestic Dealer Network (42 Dealers)",
      },
      {
        id: "international",
        name: "International",
        tagline: "Export distribution across 83 Dealers across the world",
        defaultScope: "world",
        primaryMetricKey: "exportCountries",
        secondaryMetricKeys: ["globalDealers", "iolsExported"],
        legendTitle: "Global Distribution (83 Dealers across the world)",
      },
    ],
    metrics: [
      { id: "nationalDealersCount", label: "Domestic Dealers (42)" },
      { id: "exportCountriesCount", label: "International Dealers (83)" },
      { id: "iolsProduced", label: "IOLs Distributed" },
      { id: "productsCount", label: "Ophthalmic Products" },
    ],
    defaultCenter: INDIA_CENTER,
    defaultZoom: 4.8,
  },
  auroitech: {
    id: "auroitech",
    name: "Auroitech",
    shortName: "Auroitech",
    tagline: "Technology",
    description:
      "Technology arm innovating digital health solutions, telemedicine platforms, vision screening AI, and hospital management software.",
    color: "#0284C7", // Cyan/Blue
    colorLight: "#38BDF8",
    bgGlow: "rgba(2, 132, 199, 0.15)",
    subcategories: [
      {
        id: "ihms",
        name: "IHMS",
        tagline: "154 Global Client Deployments across 12 Nations",
        defaultScope: "world",
        primaryMetricKey: "ihmsDeployments",
        secondaryMetricKeys: ["hospitalsConnected", "dailyTransactions"],
        legendTitle: "IHMS Global Client Deployments (154 Sites)",
      },
      {
        id: "eyenotes",
        name: "Eyenotes",
        tagline: "184 Global EMR Deployments across Nations",
        defaultScope: "world",
        primaryMetricKey: "eyenotesUsers",
        secondaryMetricKeys: ["emrRecords", "activeDoctors"],
        legendTitle: "Eyenotes EMR Deployments (184 Sites)",
      },
      {
        id: "vcms",
        name: "VCMS",
        tagline: "398 Vision Centres across Bangladesh (222), India (170) & Nepal (6)",
        defaultScope: "world",
        primaryMetricKey: "vcmsCentres",
        secondaryMetricKeys: ["teleconsultations", "ruralScreenings"],
        legendTitle: "VCMS Rural Network (398 Centres)",
      },
      {
        id: "total_patients",
        name: "Total Patients Registered",
        tagline: "Digital health patient registration & screenings",
        defaultScope: "state",
        primaryMetricKey: "totalPatientsRegistered",
        secondaryMetricKeys: ["screeningRecords", "digitalPrescriptions"],
        legendTitle: "Digital Patient Registry",
      },
    ],
    metrics: [
      { id: "clientInstitutionsCount", label: "Client Hospitals" },
      { id: "digitalPatientsCount", label: "Patients Registered" },
      { id: "productsDeployedCount", label: "Software Solutions" },
      { id: "teleconsultsCount", label: "Telemedicine Consults" },
    ],
    defaultCenter: INDIA_CENTER,
    defaultZoom: 5.0,
  },
  eyebank: {
    id: "eyebank",
    name: "Rotary Aravind International Eye Bank",
    shortName: "Eye Bank",
    tagline: "Vision Restoration",
    description:
      "Premier eye bank network dedicated to corneal tissue retrieval, processing, evaluation, distribution, and corneal blindness eradication.",
    color: "#059669", // Emerald Green
    colorLight: "#34D399",
    bgGlow: "rgba(5, 150, 105, 0.15)",
    subcategories: [
      {
        id: "collected",
        name: "Collected",
        tagline: "District-wise tissue collection across 7 Eye Bank Centres",
        defaultScope: "state",
        primaryMetricKey: "collectionCentres",
        secondaryMetricKeys: ["districtsCovered", "donationsCount"],
        legendTitle: "District Collection Hubs",
      },
      {
        id: "distributed",
        name: "Distributed",
        tagline: "Collected eyes distribution network across India",
        defaultScope: "country",
        primaryMetricKey: "transplantsCount",
        secondaryMetricKeys: ["destinationsCount", "statesCovered"],
        legendTitle: "National Tissue Distribution Network",
      },
      {
        id: "collection_vs_utilisation",
        name: "Collection vs Utilisation",
        tagline: "10-Year AIEBS collection & utilization trend analysis",
        defaultScope: "country",
        primaryMetricKey: "annualCollection",
        secondaryMetricKeys: ["annualUtilization", "utilizationRate"],
        legendTitle: "10-Year Collection vs Utilisation",
      },
    ],
    metrics: [
      { id: "collectionCentresCount", label: "Collection Centres (7)" },
      { id: "corneasCollectedAnnual", label: "Corneas Collected (6,897/Yr)" },
      { id: "transplantsAnnual", label: "Transplants Utilised (2,670/Yr)" },
      { id: "pledgesCount", label: "Utilization Rate (38.7%)" },
    ],
    defaultCenter: [78.1198, 9.9252],
    defaultZoom: 6.0,
  },
};
